### ISSUE TITLE
プロジェクト構成の見直し

### ISSUE THREAD

**Issue by ryutah** [mwwolf/mwwolf#17]
## Why

mockallや、analyzerのエラーなど、workspace分割をする上での弊害が多発してきた。
crateをここまでの粒度で分割するのがベストプラクティスなのかも不明な現状、開発的な問題をへらすためにも、workspaceの活用方法を見直したほうが良さそうとなった

## Todo

- backend, frontendというworkspaceにするようにする
  - [x] backend
  - [x] frontend
  - [x] application

**Comment by qwerty2501** [comment]
DONE
