### ISSUE TITLE
WebRTC調査 参照実装をする

### ISSUE THREAD

**Issue by ryutah** [mwwolf/mwwolf#22]
## Todo

- https://github.com/codec-abc/Yew-WebRTC-Chat コードリーディング
- 上記リポジトリのコードを動かしてみる
- コードを参考に、参照実装をしてみる

---

refs #20

**Comment by qwerty2501** [comment]
WebRTCのnegotiationについて調査する

**Comment by ryutah** [comment]
https://github.com/anykao/yew-firebase-service この辺参考に、Firestoreを使って実装するイメージかな？

**Comment by ryutah** [comment]
とりあえず、実装方針なんとなく定まったのでClose
