### ISSUE TITLE
イベントストーミングする

### ISSUE THREAD

**Issue by qwerty2501** [mwwolf/mwwolf#29]
https://jamboard.google.com/d/1smAhF-l2nYJFiuOokTIh9UcHHzhDotkESaZxKb5SZpY/viewer?f=0

参考:
- https://zenn.dev/tkatsuma/articles/97931405cbcd94
- https://qiita.com/tsukmr/items/91f5be9ba1004c19ec26#%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%82%B9%E3%83%88%E3%83%BC%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%AE%E9%80%B2%E3%82%81%E6%96%B9
- https://speakerdeck.com/yoskhdia/lets-try-eventstorming?slide=3

**Comment by ryutah** [comment]
よくわかんなかった！
